name: Sneaker Bot Daily Run

on:
  schedule:
    - cron: '0 16 * * *'  # Runs daily at 16:00 UTC
  workflow_dispatch:     # Allows manual run from GitHub UI

jobs:
  run-sneaker-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: stable

      - name: Check Chrome & ChromeDriver versions
        run: |
          google-chrome --version
          chromedriver --version

      - name: Run sneaker bot script
        env:
          consumer_key: ${{ secrets.consumer_key }}
          consumer_secret: ${{ secrets.consumer_secret }}
          access_token: ${{ secrets.access_token }}
          access_token_secret: ${{ secrets.access_token_secret }}
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 &
          sleep 3  # give xvfb time to start
          python postToX.py
