name: Sneaker Bot Daily Run

on:
  schedule:
    - cron: '0 17 * * *'  
  workflow_dispatch:     

jobs:
  run-sneaker-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11   # Selenium stable with 3.11, avoid 3.13 for now

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Chromedriver
        run: |
          sudo apt-get install -y chromium-chromedriver

      - name: Run sneaker bot script
        env:
          consumer_key: ${{ secrets.consumer_key }}
          consumer_secret: ${{ secrets.consumer_secret }}
          access_token: ${{ secrets.access_token }}
          access_token_secret: ${{ secrets.access_token_secret }}
        run: python postToX.py
