name: Sneaker Bot Daily Run

on:
  schedule:
    - cron: '0 16 * * *'  # Runs daily at 16:00 UTC
  workflow_dispatch:     # Allows manual run

jobs:
  run-sneaker-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Google Chrome
        run: |
          CHROME_VERSION=138.0.7204.183
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          google-chrome --version

      - name: Install matching ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: 138.0.7204.183

      - name: Run sneaker bot
        env:
          consumer_key: ${{ secrets.consumer_key }}
          consumer_secret: ${{ secrets.consumer_secret }}
          access_token: ${{ secrets.access_token }}
          access_token_secret: ${{ secrets.access_token_secret }}
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 &
          python postToX.py
